# Generated by Django 3.0 on 2021-06-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('E2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E2.Order_Detail')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E2.Order_Header')),
            ],
        ),
    ]
