# Generated by Django 3.0 on 2021-06-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E2', '0002_order_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Priority',
        ),
    ]
