# Generated by Django 3.0 on 2021-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E2', '0003_delete_order_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA_PDF_Ready_Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF_ID', models.IntegerField(blank=True, db_column='PDF_ID', null=True)),
                ('PDF_Flag', models.BooleanField(blank=True, db_column='PDF_Flag', null=True)),
            ],
        ),
    ]
