# Generated by Django 3.0 on 2021-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E2', '0004_qa_pdf_ready_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_pdf_ready_flag',
            name='PDF_Flag',
        ),
        migrations.RemoveField(
            model_name='qa_pdf_ready_flag',
            name='PDF_ID',
        ),
        migrations.AddField(
            model_name='qa_pdf_ready_flag',
            name='pdf_flag',
            field=models.BooleanField(blank=True, db_column='pdf_flag', null=True),
        ),
        migrations.AddField(
            model_name='qa_pdf_ready_flag',
            name='pdf_id',
            field=models.IntegerField(blank=True, db_column='pdf_id', null=True),
        ),
    ]
