# Generated by Django 3.0 on 2021-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E2', '0005_auto_20210810_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAPDFReadyFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.IntegerField(blank=True, db_column='pdf_id', null=True)),
                ('pdf_flag', models.BooleanField(blank=True, db_column='pdf_flag', null=True)),
            ],
            options={
                'db_table': 'QA_PDF_Ready_Flag',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='QA_PDF_Ready_Flag',
        ),
    ]
