# Generated by Django 3.2 on 2022-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(default='N/A', max_length=20, null=True, verbose_name='part_number')),
                ('job_number', models.CharField(default='N/A', max_length=20, null=True, verbose_name='part_number')),
                ('gl_account', models.CharField(default='N/A', max_length=20, null=True, verbose_name='gl_account')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='closed_date')),
                ('artwork', models.CharField(default='N/A', max_length=20, null=True, verbose_name='artwork')),
                ('panel', models.CharField(default='N/A', max_length=20, null=True, verbose_name='panel')),
                ('quadrant', models.CharField(default='N/A', max_length=20, null=True, verbose_name='quadrant')),
                ('quantity', models.IntegerField(null=True, verbose_name='quantity')),
                ('failed', models.IntegerField(null=True, verbose_name='failed')),
                ('failed_percent', models.FloatField(null=True, verbose_name='failed_percent')),
                ('pcb_damage', models.IntegerField(null=True, verbose_name='pcb_damage')),
                ('misc_mechanical', models.IntegerField(null=True, verbose_name='misc_mechanical')),
                ('IL_failure', models.IntegerField(null=True, verbose_name='IL_failure')),
                ('AB_failure', models.IntegerField(null=True, verbose_name='AB_failure')),
                ('VSWR_failure', models.IntegerField(null=True, verbose_name='vswr_failure')),
                ('ISO_failure', models.IntegerField(null=True, verbose_name='ISO_failure')),
            ],
        ),
    ]
