# Generated by Django 3.2 on 2022-04-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_organizationapikey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationAPIKey',
            new_name='SPCDataAPIKey',
        ),
    ]
