# Generated by Django 3.2 on 2022-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_organizationapikey_spcdataapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spcdata',
            name='AB_failure',
            field=models.IntegerField(default=0, verbose_name='AB_failure'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='IL_failure',
            field=models.IntegerField(default=0, verbose_name='IL_failure'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='ISO_failure',
            field=models.IntegerField(default=0, verbose_name='ISO_failure'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='VSWR_failure',
            field=models.IntegerField(default=0, verbose_name='vswr_failure'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='job_number',
            field=models.CharField(default='N/A', max_length=20, null=True, verbose_name='job_number'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='misc_mechanical',
            field=models.IntegerField(default=0, verbose_name='misc_mechanical'),
        ),
        migrations.AlterField(
            model_name='spcdata',
            name='pcb_damage',
            field=models.IntegerField(default=0, verbose_name='pcb_damage'),
        ),
    ]
