# Generated by Django 3.2 on 2022-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20220425_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcdata',
            name='quadrant',
        ),
        migrations.AddField(
            model_name='spcdata',
            name='PB_failure',
            field=models.IntegerField(default=0, verbose_name='PB_failure'),
        ),
        migrations.AddField(
            model_name='spcdata',
            name='lot',
            field=models.CharField(default='N/A', max_length=20, null=True, verbose_name='lot'),
        ),
        migrations.AddField(
            model_name='spcdata',
            name='sector',
            field=models.CharField(default='N/A', max_length=20, null=True, verbose_name='sector'),
        ),
    ]
