# Generated by Django 3.2 on 2021-12-22 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble_Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('application_type', models.CharField(choices=[('ATE Application', 'ATE Application'), ('Windows Application', 'Windows Application'), ('Web Application', 'Web Application'), ('Database Application', 'Database Application'), ('E2 Application', 'E2 Application'), ('QA Process Priority', 'QA Process Priority'), ('Stockroom Process Priority', 'Stockroom Process Priority'), ('Windows Label Maker', 'Windows Label Maker'), ('Robot Test Fixture', 'Robot Test Fixture'), ('ATE Test Fixture', 'ATE Test Fixture'), ('Manfacturing Test Fixture', 'Manfacturing Test Fixture'), ('Inventory Application', 'Inventory Application')], db_column='application_type', max_length=100)),
                ('trouble_status', models.CharField(db_column='trouble_status', max_length=20)),
                ('trouble_type', models.CharField(choices=[('Server Error 500', 'Server Error 500'), ('Server Not Running', 'Server Not Running'), ('PDF not Moving to Network', 'PDF not Moving to Network'), ('Item not Closing', 'Item not Closing'), ('Date Error', 'Date Error'), ('Date Code Error', 'Date Code Error'), ('C of C Scaling', 'C of C Scaling'), ('Label Scaling', 'Label Scaling'), ('Label Maker Software', 'Label Maker Software'), ('E2 Failure', 'E2 Failure'), ('Database Error', 'Database Error'), ('Printer Error', 'Printer Error'), ('Printer Low', 'Printer Low'), ('Network Error', 'Network Error'), ('Windows Error', 'Windows Error'), ('Misc', 'Misc')], db_column='trouble_type', max_length=100)),
                ('job_number', models.CharField(default='N/A', max_length=50, null=True, verbose_name='job_number')),
                ('part_number', models.CharField(default='N/A', max_length=50, null=True, verbose_name='part_number')),
                ('packing_slip', models.CharField(default='N/A', max_length=50, null=True, verbose_name='packing_slip')),
                ('open_time', models.DateTimeField(blank=True, db_column='open_time', null=True)),
                ('description', models.CharField(default='N/A', max_length=500, null=True, verbose_name='description')),
                ('solution', models.CharField(default='N/A', max_length=500, null=True, verbose_name='solution')),
                ('reported_by', models.CharField(default='N/A', max_length=50, null=True, verbose_name='reported_by')),
                ('location', models.CharField(choices=[('Stock Room', 'Stock Room'), ('Inspection', 'Inspection'), ('Shipping', 'Shipping'), ('Sales', 'Sales'), ('Test', 'Test'), ('Manfacturing', 'Manfacturing'), ('Machine Shop', 'Machine Shop')], default='N/A', max_length=100, null=True, verbose_name='location')),
                ('close_time', models.DateTimeField(blank=True, db_column='close_time', null=True)),
                ('update_by', models.CharField(default='N/A', max_length=50, verbose_name='update_by')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'trouble_ticket',
                'managed': True,
            },
        ),
    ]
