# Generated by Django 3.2 on 2021-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportQueue',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reportname', models.CharField(blank=True, db_column='ReportName', max_length=50, null=True)),
                ('reporttype', models.CharField(blank=True, db_column='ReportType', max_length=50, null=True)),
                ('reportstatus', models.CharField(blank=True, db_column='ReportStatus', max_length=50, null=True)),
                ('jobnumber', models.CharField(blank=True, db_column='JobNumber', max_length=50, null=True)),
                ('workstation', models.CharField(blank=True, db_column='WorkStation', max_length=50, null=True)),
                ('partnumber', models.CharField(blank=True, db_column='PartNumber', max_length=50, null=True)),
                ('operator', models.CharField(blank=True, db_column='Operator', max_length=50, null=True)),
                ('activedate', models.DateTimeField(blank=True, db_column='ActiveDate', null=True)),
            ],
        ),
    ]
