# Generated by Django 3.2 on 2021-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0002_reportqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportqueue',
            name='percentcomlete',
            field=models.FloatField(null=True, verbose_name='PercentComplete'),
        ),
    ]
