# Generated by Django 3.2 on 2021-09-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0003_reportqueue_percentcomlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportqueue',
            name='percentcomlete',
        ),
    ]
