# Generated by Django 3.2 on 2021-09-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0004_remove_reportqueue_percentcomlete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportqueue',
            options={'managed': False},
        ),
    ]
