# Generated by Django 3.2 on 2021-09-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0005_alter_reportqueue_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportqueue',
            table='',
        ),
    ]
