# Generated by Django 3.2 on 2021-11-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0006_alter_reportqueue_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportqueue',
            table='ReportQueue',
        ),
    ]
