# Generated by Django 3.2 on 2022-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0007_alter_reportqueue_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(blank=True, db_column='PartNumber', max_length=255, null=True)),
                ('fixturenumber', models.CharField(blank=True, db_column='fixturenumber', max_length=255, null=True)),
                ('plunger', models.CharField(blank=True, db_column='plunger', max_length=255, null=True)),
                ('revision', models.CharField(blank=True, db_column='revision', max_length=255, null=True)),
                ('fixnum', models.IntegerField(db_column='fixnum')),
            ],
        ),
    ]
