# Generated by Django 3.2 on 2022-05-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0008_testfixtures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfixtures',
            options={'managed': False},
        ),
    ]
